import { TweetCard } from './TweetCard'
import { SkeletonCard } from './SkeletonCard'
import { AI_MODELS } from '../types'
import type { GenerateResults, TweetOption } from '../types'

interface ResultsSectionProps {
  results: GenerateResults
  pillar: string
  isLoading: boolean
  postedOptionKeys: Set<string>
  onSelectTweet: (tweet: TweetOption, source: 'Claude' | 'OpenAI', optionKey: string) => void
}

export function ResultsSection({ results, pillar, isLoading, postedOptionKeys, onSelectTweet }: ResultsSectionProps) {
  const modelMeta = AI_MODELS.find((m) => m.value === results.model)
  const source: 'Claude' | 'OpenAI' = results.model === 'claude' ? 'Claude' : 'OpenAI'

  return (
    <div>
      <div className="flex flex-col gap-2 mb-4 sm:flex-row sm:items-center sm:gap-3">
        <h2 className="text-foreground">Generated Options</h2>
        {modelMeta && !isLoading && (
          <span
            className={`text-xs px-2.5 py-1 rounded-full font-semibold border ${modelMeta.badgeClass}`}
          >
            Generated by {modelMeta.badge}
          </span>
        )}
        {results.generatedAt && !isLoading && (
          <span className="text-xs text-muted-foreground sm:ml-auto">
            {new Date(results.generatedAt).toLocaleTimeString()}
          </span>
        )}
      </div>

      <div className="flex flex-col gap-4">
        {isLoading ? (
          <>
            <SkeletonCard />
            <SkeletonCard />
            <SkeletonCard />
          </>
        ) : (
          results.options.map((tweet, i) => {
            const optionKey = `${results.generatedAt}-${i}`
            return (
              <TweetCard
                key={optionKey}
                tweet={tweet}
                pillar={pillar}
                source={source}
                isPosted={postedOptionKeys.has(optionKey)}
                onSelect={(t) => onSelectTweet(t, source, optionKey)}
              />
            )
          })
        )}
      </div>
    </div>
  )
}
